In [1]:
import numpy as np
import pandas as pd

In [2]:


df = pd.DataFrame({
    "Name": ["Amit", "Rahul", "Neha", "Priya", "Rohit"],
    "Department": ["IT", "HR", "IT", "HR", "IT"],
    "Salary": [50000, 40000, 60000, 45000, 55000]
})

print(df)

    Name Department  Salary
0   Amit         IT   50000
1  Rahul         HR   40000
2   Neha         IT   60000
3  Priya         HR   45000
4  Rohit         IT   55000

In [9]:
cat = df.groupby("Department")['Salary'].sum()
cat

Department
HR     85000
IT    165000
Name: Salary, dtype: int64

In [7]:
for i,v in cat:
    print(i,v)

HR     Name Department  Salary
1  Rahul         HR   40000
3  Priya         HR   45000
IT     Name Department  Salary
0   Amit         IT   50000
2   Neha         IT   60000
4  Rohit         IT   55000

In [13]:
m =df['Salary'].mean()
m

np.float64(50000.0)

In [15]:
df['Salary'].agg(["sum","mean","median","min","max","count"])

sum       250000.0
mean       50000.0
median     50000.0
min        40000.0
max        60000.0
count          5.0
Name: Salary, dtype: float64

Pivot table

In [21]:


data = {
    "Salesperson": ["Alice", "Bob", "Alice", "Charlie", "Bob", "Alice"],
    "Region": ["East", "West", "East", "East", "West", "West"],
    "Product": ["Laptop", "Laptop", "Mouse", "Laptop", "Mouse", "Laptop"],
    "Sales": [1200, 1500, 200, 1000, 300, 800]
}

df = pd.DataFrame(data)

print(df)

  Salesperson Region Product  Sales
0       Alice   East  Laptop   1200
1         Bob   West  Laptop   1500
2       Alice   East   Mouse    200
3     Charlie   East  Laptop   1000
4         Bob   West   Mouse    300
5       Alice   West  Laptop    800

In [23]:
pd.pivot_table(df,values="Sales",index="Region",columns="Product" ,aggfunc='median')

Product  Laptop  Mouse
Region
East     1100.0  200.0
West     1150.0  300.0

Cross tab

In [24]:
pd.crosstab(df['Region'],df['Product'])

Product  Laptop  Mouse
Region
East          2      1
West          2      1